### ISSUE TITLE
Using CreateSession for a private app

### ISSUE THREAD

**Issue by thurstjo63** [microapps/Nodify-Shopify#34]
Hi, I'm using nodify.createSession for a private app. I know that unlike in public apps, one doesn't need to use Oauth to authenticate the client as the apiKey and secret are already generated for me. My question is in the createSession call what do I need to put as the argument for the last argument (i.e. createSession(MyShop.myshopify.com, ourAPIkey, ourSecret, persistentOauth2Token)?

I'm wondering whether it is consistent with the PHP Shopify API skeleton app that I saw where true was the last parameter or should I include a token irrespective of this being a private app.

Thanks in advance,

John

**Comment by Alua-Kinzhebayeva** [comment]
Hi! I will get back to you.

**Comment by Alua-Kinzhebayeva** [comment]
Hi @thurstjo63! If it is still relevant to you, I have updated an API to be able to create a session for a private app. It is not on npmjs yet, just here on Github.
```
var nodify = require('nodify-shopify');
session = nodify.createPrivateAppSession("your-shop-name", "your-api-key", "your-password");
session.orders.all({limit: 5}, function(err, orders){
    if(err) { console.log(orders); throw err;}
    console.log(orders);
}); 
```
