### ISSUE TITLE
Travis PR integration broken

### ISSUE THREAD

**Issue by lpinca** [microapps/Nodify-Shopify#49]
It seems that there is an issue with the Travis integration in the latest PRs.
Travis still [runs](https://travis-ci.org/microapps/Nodify-Shopify/pull_requests) but the build is not visible inline in the PRs (#46, #47, #48).

I wonder if this happened when the repository has been renamed.

**Comment by Alua-Kinzhebayeva** [comment]
I guess the problem is related to renaming of the repository.

**Comment by Alua-Kinzhebayeva** [comment]
+ it is missing some info for publishing npmjs

**Comment by lpinca** [comment]
> It is missing some info for publishing npmjs

That's another issue.

**Comment by lpinca** [comment]
@Alua-Kinzhebayeva can you try to sync the repositories on Travis and disable / reenable Nodify-Shopify?

**Comment by Alua-Kinzhebayeva** [comment]
That is my plan

**Comment by Alua-Kinzhebayeva** [comment]
closing this issue due to being fixed in PR #51. the problem was with the Travis variable was not being set. https://gyazo.com/3e594dc7cf5116045011c1c4bd0946f4

**Comment by lpinca** [comment]
Perfect, thank you.
