### ISSUE TITLE
Add this project/repo to opensourceforshopify.com

### ISSUE THREAD

**Issue by alexandresaiz** [microapps/Nodify-Shopify#55]
Find instructions on how to here: https://github.com/discolabs/opensourceforshopify.com#adding-your-repository

**Comment by Alua-Kinzhebayeva** [comment]
Added this module to opensourceforshopify.com
https://gyazo.com/9f367f910eeb7a518f44b7dde430666c

**Comment by iamandrebulatov** [comment]
[http://opensourceforshopify.com](http://opensourceforshopify.com) seems down and I don't see **Nodify-Shopify** on [http://shopify.github.io/](http://shopify.github.io/)

**Comment by lpinca** [comment]
@iamandrebulatov http://shopify.github.io/ only lists official Shopify projects.
Regarding http://opensourceforshopify.com, we should probably create an issue here https://github.com/discolabs/opensourceforshopify.com.
