### ISSUE TITLE
TypeError: Shopify is not a function

### ISSUE THREAD

**Issue by Jan-Jan** [microapps/Nodify-Shopify#86]
Hi, I get this error when I try to use this library:
```
const shopify = new Shopify('funkyshop.myshopify.com', 'asdf21351vfe', 'ssdafqr52fq24d1');
                ^

TypeError: Shopify is not a function
```

which is in reference to

```
const Shopify = require('nodify-shopify');
const shopify = new Shopify('funkyshop.myshopify.com', 'asdf21351vfe', 'ssdafqr52fq24d1');
```

PS. Thank you for the application, I can see being very useful.
PPS. apiKeys, passwords, etc changed to protect the innocent ;-)

**Comment by lpinca** [comment]
The master branch is not published on npm. Try to install the lib like this:
```
npm install microapps/nodify-shopify
```
and see if this fixes the issue.

**Comment by Jan-Jan** [comment]
working :-) thank you

Would you like to create a pull request so you can add that to the README?

**Comment by lpinca** [comment]
We want to publish an alpha version on npm, but we are not sure what name to use, see #84.

**Comment by lpinca** [comment]
It may still be useful to fix the doc until we actually publish to npm so feel free to file a pr.
Thank you.

**Comment by Jan-Jan** [comment]
done
